package br.com.cgvargas.forumHub.dominios.cursos;

public enum Categorias {
    ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS,
    DESENVOLVIMENTO_BACKEND,
    DESENVOLVIMENTO_FRONTEND,
    ANALISE_DE_DADOS,
    BANCO_DE_DADOS,
    ARQUITETURA_DE_SOFTWARE,
    PARADIGMAS_DE_PROGRAMACAO,
    REDES_DE_COMPUTADORES,
    IA_GENERATIVA,
    BLOCKCHAIN,
    REALIDADE_AUMENTADA_E_VIRTUAL,
    CIBERSEGURANCA,
    DESENVOLVIMENTO_MOBILE,
    CIENCIA_DE_DADOS,
    ENGENHARIA_DE_DADOS,
    TESTES_AUTOMATIZADOS,
    IOT,
    APRENDIZAGEM_AUTOMATICA,
    ETICA_E_PRIVACIDADE_DIGITAL;
}

